/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import demo.models.CinemaHall;

public class App {

  public String getGreeting() {
    return "Hello shubham singhal!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
